### ISSUE TITLE
dependencies not included in binary?

### ISSUE THREAD

**Issue by kiprasmel** [tsoding/boomer#110]
After building, I copied `boomer` into `/usr/local/bin/`. I tried launching it outside of the repo directory, and it worked, but not always!

Sometimes it did this:

```sh
$ boomer

/home/kipras/forkprojects/boomer/src/boomer.nim(32) boomer
/home/kipras/forkprojects/boomer/src/boomer.nim(28) readShader
/usr/lib/nim/system/io.nim(842) readFile
Error: unhandled exception: cannot open: src/vert.glsl [IOError]

```

it seems to me that the `boomer` executable tries to load some other modules from the source directory, but fails to do so?

Adding the boomer's directory to the $PATH seems to solve the issue (verifying right now). Any chances to debug this mess?

**Comment by rexim** [comment]
@kiprasmel tried to address your concerns in 3e8c24a4a4a7e39d419315bdc822e750cdc4957a Please let me know if you have any other questions regarding that and close the issue if everything's clear. Thank you for filing this issue!

**Comment by kiprasmel** [comment]
Oh, that explains everything perfectly -- thanks @rexim!
