### ISSUE TITLE
Nimble build fails on arch linux (again)

### ISSUE THREAD

**Issue by anzix** [tsoding/boomer#126]
OS: Arch Linux (6.5.6-zen2-1-zen)
Package dependencies:
`nim 2.0.0-2`
`libxrandr 1.5.4-1`, `lib32-libxrandr 1.5.3-1`
`mesa 23.2.1-2`, `lib32-mesa 23.2.1-2`
`libx11 1.8.7-1`, `lib32-libx11 1.8.7-1`
`libxext 1.3.5-1`, `lib32-libxext 1.3.5-1`
`libxrandr 1.5.4-1`, `lib32-libxrandr 1.5.3-1`
nimble build fails with the following error message:

```
$ nimble build
  Verifying dependencies for boomer@0.0.1
     Info:  Dependency on x11@#30b3a190ef9ec1621c53d501b4da0133281f108e already satisfied
  Verifying dependencies for x11@1.1
     Info:  Dependency on opengl@>= 1.2.3 already satisfied
  Verifying dependencies for opengl@1.2.9
     Info:  Dependency on x11@>= 1.1 already satisfied
  Verifying dependencies for x11@1.1
   Building boomer/boomer using c backend
/home/user/Repos/boomer/src/config.nim(1, 8) Warning: imported and not used: 'macros' [UnusedImport]
/home/user/.nimble/pkgs2/opengl-1.2.9-87ece9f3a9f99d17332b50885e15a4dcb18c51b5/opengl/glx.nim(74, 14) Error: undeclared identifier: 'XID'
       Tip: 11 messages have been suppressed, use --verbose to show them.
nimble.nim(229)          buildFromDir

    Error:  Build failed for the package: boomer
```

**Comment by rexim** [comment]
istg I need to rewrite it in C. These hipster toy langs keep changing shit I depend on.

**Comment by kovdan01** [comment]
For those who still have troubles during build (particularly, `boomer/src/screenshot.nim(39, 48) Error: undeclared identifier: 'Window'` - remove your nimble folder (`.nimble` or `.local/share/nimble`). They don't migrate its contents automatically. This should resolve the issue.
