### ISSUE TITLE
challenge: implement something similar for wayland

### ISSUE THREAD

**Issue by haxfn** [tsoding/boomer#134]
Currently seems impossible, but would love to work on building one

1. sway-wiki: https://github.com/swaywm/sway/wiki#screen-zooming-feature
2. sway-issues: https://github.com/swaywm/sway/issues/2781

**Comment by kkkfasya** [comment]
here: https://github.com/coffeeispower/woomer  
or for anyone that uses gnome use my modified version instead https://github.com/kkkfasya/coomer

**Comment by haxfn** [comment]
This is great, @kkkfasya !!
