### ISSUE TITLE
Document thirdparty system dependencies in README

### ISSUE THREAD

**Issue by rexim** [tsoding/boomer#65]
Derived from https://github.com/tsoding/boomer/issues/64#issuecomment-560020955

**Comment by SolitudeSF** [comment]
#64 shouldn't be a problem once https://github.com/nim-lang/opengl/pull/74 is merged.

**Comment by SolitudeSF** [comment]
it is done

**Comment by rexim** [comment]
@SolitudeSF cool! Thank you very much for that Pull Request! But the system dependencies have to be documented anyway. :)
