### ISSUE TITLE
No idea what the keys are and how to personalize settings with config.

### ISSUE THREAD

**Issue by Antzelino** [tsoding/boomer#66]
What are the keys we can use and what does each do?

Also I want to change some settings because its zooming too fast for my liking, and I know I should have a config file in ~/.config/boomer/ but I don't know what settings I can change and what the format of the file should be.

**Comment by rexim** [comment]
@Antzelino Hi! Unfortunately the application is in an active development state and is not even alpha yet. Use it at your own risk. Nothing is documented, anything can be changed at any moment or stop working at all.

Right now I can only recommend to look at the code to learn about how to use this application:

- Some keybindings: https://github.com/tsoding/boomer/blob/8e8f37fa0a222c807d35f5192bedbdc2f4851b65/src/boomer.nim#L315
- Configuration: https://github.com/tsoding/boomer/blob/8e8f37fa0a222c807d35f5192bedbdc2f4851b65/src/config.nim

Sorry for any inconveniences. When the app stabilizes I will announce that publicly.

**Comment by rexim** [comment]
@Antzelino add [Controls](https://github.com/tsoding/boomer#controls) and [Configuration](https://github.com/tsoding/boomer#configuration) sections to the README. Please let me know if you still have any question. If everything is clear, please close this issue.

**Comment by Antzelino** [comment]
Everything looks clear now! Closing issue.
