### ISSUE TITLE
Boomer captures the program launcher rofi

### ISSUE THREAD

**Issue by jappeace** [tsoding/boomer#71]
I didn't expect rofi (app launcher) to be part of the screenshot:

![bug](https://user-images.githubusercontent.com/3874017/70169205-a4a98780-16ca-11ea-914e-e7798785b049.png)

**Comment by rexim** [comment]
It's probably happening because the launcher doesn't die immediately after starting the application. Possible solutions:
1. Add an optional delay to the boomer
2. Make boomer wait for some kind of event (for example, key press)

**Comment by rexim** [comment]
@jappeace hey! We introduced a delay flag in #94. Please let me know if it works for you?

**Comment by jappeace** [comment]
Hi @rexim, I tested it out, unfortunately I don't think it works in rofi, it does work in the terminal. But I bound it to a key in i3 and now everything works perfectly. You don't have to fix this for me at least.

**Comment by rexim** [comment]
@jappeace what version of rofi do you use btw?

**Comment by jappeace** [comment]
1.5.4

but I really think it's because of the compositor having a fade-out effect

**Comment by rexim** [comment]
@jappeace 
> When I tried boomer with the delay from rofi it just wouldn't start.
What was the command line you typed into rofi?

**Comment by jappeace** [comment]
![image](https://user-images.githubusercontent.com/3874017/72349021-fedf3480-36db-11ea-9115-7f8b3e8c7c32.png)

**Comment by SolitudeSF** [comment]
try launching it not from a combi mode, but plain run mode.

**Comment by jappeace** [comment]
@SolitudeSF yeah that works, but why?

**Comment by SolitudeSF** [comment]
combi cant know what mode the text you enter belongs to unless it strictly matches, so it does nothing instead.

**Comment by rexim** [comment]
@jappeace if your problem is resolved, please close this issue.
